### ISSUE TITLE
foodcritic error on cookbook under supermarket.chef.io

### ISSUE THREAD

**Issue by siwy202** [martinb3/xmledit-cookbook#6]
Looks like the cookbook located under supermarket.chef.io is missing metadata.rb.

Please see error here:  https://supermarket.chef.io/cookbooks/xmledit#foodcritic

**Comment by martinb3** [comment]
Hello! My understanding is that foodcritic via supermarket is basically unusable at this point. This is because the tarball uploaded as a release is not the same as cloning the source repository and running foodcritic.

You're running into the fact that Supermarket requires metadata.json (and chef server and chef client all use metadata.json), but Foodcritic uses metadata.rb. See these issues for more information:

https://github.com/opscode-cookbooks/openssl/issues/9
https://github.com/sethvargo/stove/issues/69

As you can see in those issues, they are going to disable the metadata.rb check on Supermarket.
